"""Ingest one PDF into the structured financial store."""

import argparse
import re
import sys

from src.extraction.pdf_router import extract_page_tables, page_needs_ocr
from src.extraction.llm_cleanup import cleanup_table
from src.store.schema import init_db
from src.store.db import add_document, add_line_item, LineItem

METRIC_SYNONYMS = {
    "total debt": "total_debt",
    "total borrowings": "total_debt",
    "borrowings": "total_debt",
    "debt": "total_debt",
    "revenue": "revenue",
    "net sales": "revenue",
    "total net sales": "revenue",
    "sales": "revenue",
    "revenue from operations": "revenue",
    "operating income": "operating_income",
    "operating profit": "operating_income",
    "ebit": "operating_income",
    "gross margin": "gross_profit",
    "gross profit": "gross_profit",
    "net income": "net_income",
    "profit after tax": "net_income",
    "cash generated by operating activities": "operating_cash_flow",
    "net cash from operating activities": "operating_cash_flow",
    "cash and cash equivalents": "cash",
    "commercial paper": "commercial_paper",
    "term debt": "term_debt",
    "accounts receivable": "accounts_receivable",
    "accounts payable": "accounts_payable",
    "inventories": "inventories",
    "total assets": "total_assets",
    "total liabilities": "total_liabilities",
    "total shareholders equity": "total_shareholders_equity",
    "total shareholders’ equity": "total_shareholders_equity",
}


def normalize_metric(raw_label: str) -> str | None:
    cleaned = " ".join(raw_label.strip().lower().split())
    direct = METRIC_SYNONYMS.get(cleaned)
    if direct:
        return direct
    slug = re.sub(r"[^a-z0-9]+", "_", cleaned).strip("_")
    return slug or None


def ingest(pdf_path: str, entity: str, doc_type: str, fiscal_year: str,
           period: str, statement: str, pages: list[int], db_path: str,
           model: str = "hermes3:8b", skip_llm_cleanup: bool = False) -> None:
    conn = init_db(db_path)
    document_id = add_document(conn, entity, doc_type, fiscal_year, pdf_path)
    stored = 0
    skipped = 0

    for page in pages:
        if page_needs_ocr(pdf_path, page):
            print(f"[page {page}] looks scanned — skipping, wire up OCR fallback first", file=sys.stderr)
            continue

        tables = extract_page_tables(pdf_path, page)
        if not tables:
            print(f"[page {page}] no table found by any extractor", file=sys.stderr)
            continue

        for table in tables:
            try:
                if skip_llm_cleanup:
                    cleaned = cleanup_table(table.rows, model=model)
                else:
                    cleaned = cleanup_table(table.rows, model=model)
            except Exception as e:
                print(f"[page {page}] cleanup failed: {e}", file=sys.stderr)
                continue

            for row in cleaned:
                metric = normalize_metric(row.get("metric_raw", ""))
                if metric is None or row.get("value") is None:
                    skipped += 1
                    continue
                add_line_item(conn, document_id, LineItem(
                    entity=entity, period=period, statement=statement,
                    metric=metric, metric_raw=row["metric_raw"], value=row["value"],
                    unit=row.get("unit") or "unspecified", consolidated=None,
                    source_page=page, source_table=table.table_caption,
                    extraction_method=table.method,
                    extraction_confidence=table.confidence,
                ))
                stored += 1

    print(f"Ingested {pdf_path} for {entity} / {period} into {db_path}")
    print(f"Stored line items: {stored}; skipped/unparsed: {skipped}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("pdf_path")
    p.add_argument("--entity", required=True)
    p.add_argument("--doc-type", required=True, choices=["10K", "annual_report", "sebi_quarterly", "sebi_annual", "investor_deck"])
    p.add_argument("--fiscal-year", required=True)
    p.add_argument("--period", required=True)
    p.add_argument("--statement", required=True, choices=["balance_sheet", "income_statement", "cash_flow"])
    p.add_argument("--pages", required=True)
    p.add_argument("--db", default="data/financials.db")
    p.add_argument("--model", default="hermes3:8b")
    p.add_argument("--skip-llm-cleanup", action="store_true")
    args = p.parse_args()

    ingest(args.pdf_path, args.entity, args.doc_type, args.fiscal_year,
           args.period, args.statement, [int(x) for x in args.pages.split(",")],
           args.db, args.model, args.skip_llm_cleanup)
